### ISSUE TITLE
What happened to branch ember-js?

### ISSUE THREAD

**Issue by James-Firth** [Casey-Forsyth/Project-Barbosa#11]
Looking [here](https://github.com/caseyvill/Project-Barbosa/network) it seems the branch ember-trips-scaffold (though I only see that in the pull request section and not in the branches page) replaced the branch ember-js.

Do we need the branch ember-js anymore or can it be removed?

**Comment by willvoutier** [comment]
yeah, i switched names on a spike and forgot to rename it before pushing, sorry. kill the original branch.

**Comment by James-Firth** [comment]
Ahh okay just got confused and wanted to make sure.
